"""Generate a single MkDocs API reference page from src/toolanything."""

from __future__ import annotations

import shutil
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = REPO_ROOT / "src" / "toolanything"
REFERENCE_ROOT = REPO_ROOT / "docs" / "reference"


def iter_modules() -> list[tuple[str, Path]]:
    modules: list[tuple[str, Path]] = []
    for path in sorted(SRC_ROOT.rglob("*.py")):
        relative = path.relative_to(SRC_ROOT)
        if path.name == "__main__.py":
            continue

        parts = list(relative.parts)
        if path.name == "__init__.py":
            module_parts = ["toolanything", *parts[:-1]]
        else:
            module_parts = ["toolanything", *Path(*parts).with_suffix("").parts]

        modules.append((".".join(module_parts), path))
    return modules


def build_title(module_name: str) -> str:
    return f"`{module_name}`"


def build_index(modules: list[tuple[str, Path]]) -> None:
    lines = [
        "<!-- Auto-generated by scripts/generate_api_docs.py. Do not edit by hand. -->",
        "# API Reference",
        "",
        "這一頁由程式自動掃描 `src/toolanything` 生成，避免 module 新增或搬移時 API 文件目錄過時。",
        "",
        "## Modules",
        "",
    ]

    for module_name, source_path in modules:
        lines.extend(
            [
                f"### {build_title(module_name)}",
                "",
                f"Source: `{source_path.relative_to(REPO_ROOT).as_posix()}`",
                "",
                f"::: {module_name}",
                "",
            ]
        )

    (REFERENCE_ROOT / "index.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    if REFERENCE_ROOT.exists():
        shutil.rmtree(REFERENCE_ROOT)
    REFERENCE_ROOT.mkdir(parents=True, exist_ok=True)

    modules = iter_modules()
    build_index(modules)

    print(f"Generated API reference for {len(modules)} modules in {REFERENCE_ROOT}")


if __name__ == "__main__":
    main()
